apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - image: ghcr.io/pis22z/frontend:latest
                  name: frontend
                  env:
                      - name: REACT_APP_API_URL
                        value: 'https://pis.rasztabiga.me/api'
                  ports:
                      - containerPort: 3000
