name: Build

on:
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Build app
              run: npm run build
            - name: Test Jest
              run: npm run test
